---
  - systemd:
      name: "{{ common_service }}"
      state: stopped 

  - name: backup catalina.out
    copy:
      src: "{{ common_path }}/logs/catalina.out"
      dest: "{{ common_path }}/logs/catalina.out.ansible.{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
      remote_src: yes
    ignore_errors: yes    # if log is not available play will run without breaking the execution

  - name: Remove catalina.out
    file:
      path: "{{ common_path }}/logs/catalina.out"
      state: absent
    ignore_errors: yes    # if log is not available play will run without breaking the execution